### ISSUE TITLE
Feature request - users should be able to secure Grafana observability route using own certificates

### ISSUE THREAD

**Issue by vadimzharov** [stolostron/multicluster-observability-operator#1164]
As of now, users are not able to configure TLS settings for the Grafana route (generate and use their own certificates) and the route is using the default OpenShift ingress certificate. There are no settings in the Observability CRD to specify a certificate for the route.
Idea is to provide users more flexibility with Grafana route configuration so they are able to configure TLS settings for the route. This can be set as a link to a secret in MultiClusterObservability CR for the Grafana route so the operator set route TLS settings using certificates from the secret.

**Comment by subbarao-meduri** [comment]
@vadimzharov Thank you for opening feature request. 

We are tracking all feature enhancement requests in Jira. 
Created https://issues.redhat.com/browse/ACM-3980 to track this, and closing here.
